name: Deployment workflows
on:
  push:
    branches:
      - main

jobs:
  back-merge-to-staging:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add merge commit to staging
        run: |
          git config user.name dluftspring
          git config user.email daniel.luftspring@brooklyndata.co
          git fetch
          git pull origin main
          git checkout staging && git pull origin staging
          git merge main --ff-only --no-edit
          git push origin staging --force


