name: CI checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  merge_group:
    branches: [ main ]

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/block-merge-based-on-time@main
        with:
          timezone: UTC
          after: "12:00"
          before: "20:00"
          base-branches: "(default)"
