name: Update release window gate

on:
  schedule:
    # Top half of every hour during week days
    - cron: "0,30 * * * 1-5"
  workflow_dispatch:


jobs:
    update-release-gate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Download release artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                workflow: release_window_002.yml
                name: release-gate
                path: release-gate.txt
                if_no_artifact_found: warn

            - name: Generate artifact
              # Check if release-gate.txt contains the word "open" or "closed"
              run: |
                    if [ ! -f release-gate.txt ]; then
                      echo "open" > release-gate.txt
                    else
                      if grep -q "open" release-gate.txt; then
                      echo "closed" > release-gate.txt
                      else
                        if grep -q "closed" release-gate.txt; then
                        echo "open" > release-gate.txt
                        else
                        fi
                      fi
                    fi

            - name: Upload release artifact
              uses: actions/upload-artifact@v3
              with:
                name: release-gate
                path: release-gate.txt